default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  timeout: 5000
  username: apps_ruby

development:
  <<: *default
  database: dra_stats

test:
  <<: *default
  database: dra_stats_test

production:
  <<: *default
  database: dra_stats
